In [12]:
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model

In [13]:
def conv_block(x, num_filters):
    x = Conv2D(num_filters, (3,3), padding="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)

    x = Conv2D(num_filters, (3,3), padding="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)

    return x

In [24]:
def build_model(shape):
    num_filters = [64, 128, 256, 512]
    inputs = Input((shape))

    skip_x = []
    x = inputs
    
    # ENCODER
    for f in num_filters:
        x = conv_block(x, f)
        skip_x.append(x)
        x = MaxPool2D((2, 2))(x)

    # BRIDGE
    x = conv_block(x, 1024)

    num_filters.reverse()
    skip_x.reverse()


    # DECODER
    for i, f in enumerate(num_filters):
        x = UpSampling2D((2,2))(x)
        xs = skip_x[i]
        x = Concatenate()([x, xs])
        x = conv_block(x, f)
    
    # OUTPUT
    x = Conv2D(1, (1,1), padding="same")(x)
    x = Activation("sigmoid")(x)

    return Model(inputs, x)

In [26]:
input_shape = (256, 256, 3)  
model = build_model(input_shape)
print(model.summary())

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_6       │ (None, 256, 256,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_72 (Conv2D)  │ (None, 256, 256,  │      1,792 │ input_layer_6[0]… │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 256, 256,  │        256 │ conv2d_72[0][0]   │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_72       │ (None, 256, 256,  │          0 │ batch_normalizat… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_73 (Conv2D)  │ (None, 256, 256,  │     36,928 │ activation_72[0]… │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 256, 256,  │        256 │ conv2d_73[0][0]   │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_73       │ (None, 256, 256,  │          0 │ batch_normalizat… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_24    │ (None, 128, 128,  │          0 │ activation_73[0]… │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_74 (Conv2D)  │ (None, 128, 128,  │     73,856 │ max_pooling2d_24… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 128, 128,  │        512 │ conv2d_74[0][0]   │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_74       │ (None, 128, 128,  │          0 │ batch_normalizat… │
│ (Activation)        │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_75 (Conv2D)  │ (None, 128, 128,  │    147,584 │ activation_74[0]… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 128, 128,  │        512 │ conv2d_75[0][0]   │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_75       │ (None, 128, 128,  │          0 │ batch_normalizat… │
│ (Activation)        │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_25    │ (None, 64, 64,    │          0 │ activation_75[0]… │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_76 (Conv2D)  │ (None, 64, 64,    │    295,168 │ max_pooling2d_25… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 64, 64,    │      1,024 │ conv2d_76[0][0] 

 Total params: 31,402,497 (119.79 MB)

 Trainable params: 31,390,721 (119.75 MB)

 Non-trainable params: 11,776 (46.00 KB)

None


In [19]:
import numpy as np

trainimageNP = np.load("../dataset/xpm_annotate/feed/train_img.npy")
trainmaskNP = np.load("../dataset/xpm_annotate/feed/train_mask.npy")
validimageNP = np.load("../dataset/xpm_annotate/feed/valid_img.npy")
validmaskNP = np.load("../dataset/xpm_annotate/feed/valid_mask.npy")

In [16]:
print(trainimageNP.shape)
print(trainmaskNP.shape)
print(validimageNP.shape)
print(validmaskNP.shape)

(122, 310, 130, 3)
(122, 310, 130)
(14, 310, 130, 3)
(14, 310, 130)


In [27]:
input_shape = (310, 130, 3)  
model = build_model(input_shape)
print(model.summary())

ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 76, 32, 512), (None, 77, 32, 256)]

In [33]:
lr = 1e-4
batchSize = 4
epochs = 50

In [42]:
from keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping

opt = tf.keras.optimizers.Adam(lr)
model.compile(loss="binary_crossentropy", optimizer = opt, metrics=["accuracy"])

stepsPerEpoch = int(np.ceil(len(trainimageNP) / batchSize))
validationSteps = int(np.ceil(len(validimageNP) / batchSize))

best_model_file = "../test/unet-cnn.keras"

callbacks = [
    ModelCheckpoint(best_model_file, verbose=1, save_best_only=True),
    ReduceLROnPlateau(monitor="val_loss", patience=5, factor=0.1, verbose=1, min_lr = 1e-7),
    EarlyStopping(monitor="val_accuracy", patience=20, verbose = 1)
]

history = model.fit(trainimageNP, trainmaskNP,
                    batch_size = batchSize,
                    epochs = epochs,
                    verbose = 1,
                    validation_data=(validimageNP, validmaskNP),
                    validation_steps = validationSteps,
                    steps_per_epoch = stepsPerEpoch,
                    shuffle = True,
                    callbacks=callbacks
                    )

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6s/step - accuracy: 0.7767 - loss: 0.4703
Epoch 1: val_loss improved from inf to 0.81173, saving model to ../test/unet-cnn.keras
31/31 ━━━━━━━━━━━━━━━━━━━━ 193s 6s/step - accuracy: 0.7787 - loss: 0.4675 - val_accuracy: 0.3918 - val_loss: 0.8117 - learning_rate: 1.0000e-04
Epoch 2/50

Epoch 2: val_loss improved from 0.81173 to 0.00000, saving model to ../test/unet-cnn.keras


c:\Users\kimbe\AppData\Local\Programs\Python\Python312\Lib\contextlib.py:158: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(value)


31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00 - learning_rate: 1.0000e-04
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5s/step - accuracy: 0.8930 - loss: 0.2677
Epoch 3: val_loss did not improve from 0.00000
31/31 ━━━━━━━━━━━━━━━━━━━━ 160s 5s/step - accuracy: 0.8930 - loss: 0.2676 - val_accuracy: 0.4205 - val_loss: 1.1365 - learning_rate: 1.0000e-04
Epoch 4/50

Epoch 4: val_loss did not improve from 0.00000
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.0000e+00 - val_loss: 0.0000e+00 - learning_rate: 1.0000e-04
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6s/step - accuracy: 0.8899 - loss: 0.2638
Epoch 5: val_loss did not improve from 0.00000
31/31 ━━━━━━━━━━━━━━━━━━━━ 179s 6s/step - accuracy: 0.8901 - loss: 0.2634 - val_accuracy: 0.5812 - val_loss: 0.6650 - learning_rate: 1.0000e-04
Epoch 6/50

Epoch 6: val_loss did not improve from 0.00000
31/31 ━━━━━━━

In [49]:
import cv2

model = tf.keras.models.load_model("../test/unet-cnn.keras")

width = 256
height = 256

imgpath = "../dataset/xpm_annotate/images/0001.png"
img = cv2.imread(imgpath)
img2 = cv2.resize(img, (width, height))
img2 = img2/255.0
img3 = np.expand_dims(img2, axis=0)

pred = model.predict(img3)
resultMask = pred[0]

print(resultMask)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[[0.52401143]
  [0.52835476]
  [0.52950084]
  ...
  [0.51894605]
  [0.5167547 ]
  [0.5198737 ]]

 [[0.52520484]
  [0.5260088 ]
  [0.52941585]
  ...
  [0.51295775]
  [0.5227168 ]
  [0.5179724 ]]

 [[0.52132535]
  [0.529012  ]
  [0.5356832 ]
  ...
  [0.5180496 ]
  [0.52668893]
  [0.5289698 ]]

 ...

 [[0.5181293 ]
  [0.49581283]
  [0.497673  ]
  ...
  [0.48283303]
  [0.4955786 ]
  [0.5097421 ]]

 [[0.5175083 ]
  [0.507305  ]
  [0.5020215 ]
  ...
  [0.49030027]
  [0.49771458]
  [0.51840407]]

 [[0.511126  ]
  [0.5070233 ]
  [0.5134216 ]
  ...
  [0.49741113]
  [0.5024809 ]
  [0.5124818 ]]]


In [50]:
resultMask[resultMask <=0.5] = 0
resultMask[resultMask > 0.5] = 255

scale_percent = 30

w = int(img.shape[1] * scale_percent/100)
h = int(img.shape[0] * scale_percent/100)

dim = (w,h)

img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
mask = cv2.resize(resultMask, dim, interpolation = cv2.INTER_AREA)

cv2.imshow("image", img)
cv2.imshow("mask", mask)
cv2.waitKey(0)

-1